#
# Copyright(C) 2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
#

# Builds all kernels.
all: is

# Builds FAST kernel.
fast:
	cd FAST && $(MAKE) all

# Builds FN kernel.
fn:
	cd FN && $(MAKE) all

# Builds GF kernel.
gf:
	cd GF && $(MAKE) all

# Builds IS kernel.
is:
	cd IS && $(MAKE) all

# Builds KM kernel.
km:
	cd KM && $(MAKE) all

# Builds LU kernel.
lu:
	cd LU && $(MAKE) all

# Builds TSP kernel.
tsp:
	cd TSP && $(MAKE) all

# Builds RT kernel.
rt:
	cd RT && $(MAKE) all

# Builds NB kernel.
nb:
	cd NB && $(MAKE) all

# Cleans compilation files.
clean:
	cd IS && $(MAKE) clean
